<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 6 DOF MANIPULATOR MODULE 
    6. Degrees of Freedom
    1. Base Rotation(yaw)
    2. Shoulder pitch
    3. shoulder roll
    4. elbow pitch
    5. wrist pitch
    6. writch roll
     + 2 DOF gripper (fingers) -->

    <!-- LINK DIMENSIONS -->

    <!-- Link6 - Shoulder Pitch -->
    <xacro:property name="link6_length" value="0.04"/>
    
    <!-- Gripper Dimensions  -->
    <xacro:property name="gripper_base_length" value="0.05"/>
    <xacro:property name="gripper_base_width" value="0.04"/>
    <xacro:property name="gripper_base_height" value="0.03"/>
    <xacro:property name="gripper_base_mass" value="0.1"/>

    <xacro:property name="finger_length" value="0.08"/>
    <xacro:property name="finger_width" value="0.015"/>
    <xacro:property name="finger_height" value="0.025"/>
    <xacro:property name="finger_mass" value="0.05"/>


    <!-- INERTIA MACRO -->

    <!-- Box inertia for Gripper Part-->
    <xacro:macro name="box_inertia" params="mass x y z">
        <inertia ixx = "${mass * (y*y + z*z)/12}"
                iyy = "${mass * (x*x + z*z)/12}"
                izz = "${mass * (x*x +y*y)/12}"
                iyz = "0.0"
                ixz = "0.0"
                ixy = "0.0" />
    </xacro:macro>

    <!-- Main Manipulator Links Macro -->
    <xacro:macro name="gripper" params="parent">
        <!-- GRIPPER BASE -->
      <link name="gripper_base">
        <visual>
          <origin xyz="0 0 ${gripper_base_length/2}" rpy="0 0 0"/>
          <geometry>
            <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
          </geometry>
          <material name="grey1"/>
        </visual>
        <collision>
          <origin xyz="0 0 ${gripper_base_length/2}" rpy="0 0 0"/>
          <geometry>
            <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${gripper_base_mass}"/>
          <xacro:box_inertia mass="${gripper_base_mass}" x="${gripper_base_length}" y="${gripper_base_width}" z="${gripper_base_height}"/>
          <origin xyz="0 0 ${gripper_base_length/2}" rpy = "0 0 0"/>
        </inertial>

      </link>

        <!-- LEFT FINGER -->
      <link name="left_finger">
        <visual>
          <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
          <geometry>
            <box size="${finger_length} ${finger_width} ${finger_height}"/>
          </geometry>
          <material name="grey1"/>
        </visual>
        <collision>
          <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
          <geometry>
              <box size="${finger_length} ${finger_width} ${finger_height}"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="${finger_mass}"/>
          <xacro:box_inertia mass="${finger_mass}" x="${finger_length}" y="${finger_width}" z="${finger_height}"/>
          <origin xyz="0 0 ${finger_length/2}" rpy = "0 0 0"/>
        </inertial>

      </link>

        <!-- RIGHT FINGER -->
        <link name="right_finger">
            <visual>
                <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
                <material name="grey1"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${finger_length} ${finger_width} ${finger_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${finger_mass}"/>
                <xacro:box_inertia mass="${finger_mass}" x="${finger_length}" y="${finger_width}" z="${finger_height}"/>
                <origin xyz="0 0 ${finger_length/2}" rpy = "0 0 0"/>
            </inertial>

        </link>

        <!-- JOINTS -->
        <!-- Link 6 to Gripper -->
        <joint name="gripper_base_joint" type="fixed">
          <parent link="${parent}"/>
          <child link="gripper_base"/>
          <origin xyz="0 0 ${link6_length}" rpy="0 0 0"/>
        </joint>

        <!-- Left Finger to Gripper Base-->
        <joint name="left_finger_joint" type="prismatic">
          <parent link="gripper_base"/>
          <child link="left_finger"/>
          <origin xyz="0 ${gripper_base_width/2 +finger_height/2} ${gripper_base_height}" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
          <dynamics damping="0.5" friction="0.5"/>
          <limit lower="0" upper="0.04"  effort="10" velocity="0.1"/>
        </joint>

        <!-- Right Finger to Gripper Base-->
        <joint name="right_finger_joint" type="prismatic">
          <parent link="gripper_base"/>
          <child link="right_finger"/>
          <origin xyz="0 ${-gripper_base_width/2 +finger_height/2} ${gripper_base_height}" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
          <dynamics damping="0.5" friction="0.5"/>
          <limit lower="0" upper="0.04"  effort="10" velocity="0.1"/>
        </joint>
    </xacro:macro>
</robot>
